KFC_Framework/Areas/admin/Controllers/managerDiscountController.cs
using KFC_Framework.Dao;
using KFC_Framework.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KFC_Framework.Areas.admin.Controllers
{
    public class managerDiscountController : Controller
    {
        KFCEntities KFCEntitiess = new KFCEntities();
        private DiscountDao discountDao = new DiscountDao();
        // GET: admin/managerDiscount
        public ActionResult Index()
        {
            if (Session["UserRole"] != null && (Session["UserRole"].ToString() == "Nhân viên" || Session["UserRole"].ToString() == "Admin"))
            {
                var list = discountDao.getListDiscount();
                return View(list);
            }
            else
            {
                TempData["Error"] = "Bạn không có quyền truy cập trang này.";
                return Redirect(Request.UrlReferrer.ToString());
            }
        }

        // GET: admin/managerDiscount/Create
        public ActionResult Create()
        {
            if (Session["UserRole"].ToString() == "Admin")
            {
                return View();
            }
            else
            {
                TempData["Error"] = "Bạn không có quyền truy cập trang này.";
                return Redirect(Request.UrlReferrer.ToString());
            }
        }

        // POST: admin/managerDiscount/Create
        [HttpPost]
        public ActionResult Create(GiamGia model)
        {
            try
            {
                discountDao.addDiscount(model);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: admin/managerDiscount/Edit/5
        public ActionResult Edit(string id)
        {
            if (Session["UserRole"].ToString() == "Admin")
            {
                GiamGia getDiscount = discountDao.getByIdDiscount(id);
                return View(getDiscount);
            }
            else
            {
                TempData["Error"] = "Bạn không có quyền truy cập trang này.";
                return Redirect(Request.UrlReferrer.ToString());
            }

        }

        // POST: admin/managerDiscount/Edit/5
        [HttpPost]
        public ActionResult Edit(GiamGia model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    discountDao.editDiscount(model);
                    return RedirectToAction("Index");
                }
                return View(model);
            }
            catch
            {
                return View();
            }
        }

        // POST: admin/managerDiscount/Delete/5
        [HttpPost]
        public ActionResult Delete(string id)
        {
            try
            {
                if (Session["UserRole"] != null && Session["UserRole"].ToString() == "Admin")
                {
                    var discount = discountDao.getByIdDiscount(id);
                    if (discount != null)
                    {
                        discountDao.delDiscount(id);
                    }
                }
                else
                {
                    TempData["Error"] = "Bạn không có quyền truy cập trang này.";
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

KFC_Framework/Areas/admin/Views/managerDiscount/Create.cshtml
@model KFC_Framework.Models.GiamGia

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/admin/Views/Shared/_LayoutAdmin.cshtml";
}

@Html.Action("_PartialErrorAccessRole", "Parital", new { area = "" })
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h3>Thêm Ưu đãi</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="mb-3 row">
            @Html.LabelFor(model => model.TenSuKien, "Tên Sự Kiện", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSuKien, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSuKien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="mb-3 row">
            @Html.LabelFor(model => model.PhanTram, "Phần Trăm", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhanTram, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhanTram, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="mb-3 row">
            @Html.LabelFor(model => model.ThongTinSuKien, "Thông Tin Sự Kiện", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ThongTinSuKien, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ThongTinSuKien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="mb-3 row">
            @Html.LabelFor(model => model.ThoiGianBD, "Thời Gian Bắt Đầu", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="date" class="form-control" id="ThoiGianBD" name="ThoiGianBD">
                @Html.ValidationMessageFor(model => model.ThoiGianBD, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="mb-3 row">
            @Html.LabelFor(model => model.ThoiGianKT, "Thời Gian Kết Thúc", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="date" class="form-control" id="ThoiGianKT" name="ThoiGianKT">
                @Html.ValidationMessageFor(model => model.ThoiGianKT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="mb-3 row">
            <div class="col-sm-2">&#160;</div>
            <div class="col-sm-10">
                <button type="submit" class="btn btn-danger fw-bold">CREATE</button>
            </div>
        </div>
        <div class="mb-3 row">
            <div class="col-sm-2">&#160;</div>
            <div class="col-sm-10">
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
}

KFC_Framework/Areas/admin/Views/managerDiscount/Edit.cshtml
@model KFC_Framework.Models.GiamGia

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/admin/Views/Shared/_LayoutAdmin.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CHỈNH SỬA ƯU ĐÃI</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaGG)

        <div class="mb-3 row">
            @Html.LabelFor(model => model.TenSuKien,"Tên Sự Kiện", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSuKien, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSuKien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="mb-3 row">
            @Html.LabelFor(model => model.PhanTram,"Phầm Trăm", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhanTram, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhanTram, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="mb-3 row">
            @Html.LabelFor(model => model.ThongTinSuKien,"Thông Tin Sự Kiện", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ThongTinSuKien, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ThongTinSuKien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="mb-3 row">
            @Html.LabelFor(model => model.ThoiGianBD, "Thời Gian Bắt Đầu", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="date" class="form-control" id="ThoiGianBD" name="ThoiGianBD" value="@Model.ThoiGianBD.ToString("yyyy-MM-dd")">
                @Html.ValidationMessageFor(model => model.ThoiGianBD, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="mb-3 row">
            @Html.LabelFor(model => model.ThoiGianKT, "Thời Gian Kết Thúc", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="date" class="form-control" id="ThoiGianKT" name="ThoiGianKT" value="@Model.ThoiGianKT.ToString("yyyy-MM-dd")">
                @Html.ValidationMessageFor(model => model.ThoiGianKT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="mb-3 row">
            <div class="col-sm-2">&#160;</div>
            <div class="col-sm-10">
                <button type="submit" class="btn btn-danger fw-bold">SAVE</button>
            </div>
        </div>
        <div class="mb-3 row">
            <div class="col-sm-2">&#160;</div>
            <div class="col-sm-10">
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
}

KFC_Framework/Areas/admin/Views/managerDiscount/Index.cshtml
@model IEnumerable<KFC_Framework.Models.GiamGia>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/admin/Views/Shared/_LayoutAdmin.cshtml";
}

@Html.Action("_PartialErrorAccessRole", "Parital", new { area = "" })
<table id="discountTable" class="table-sm table table-striped table-light table-hover custom-thead-color">
    <thead class="table-dark">
        <tr>
            <th>
                Mã Giảm giá
            </th>
            <th>
                Tên Sự Kiên
            </th>
            <th>
                Phần Trăm
            </th>
            <th>
                Thời Gian Bắt Đầu
            </th>
            <th>
                Thời Gian Kết Thúc
            </th>
            <th scope="col">&#160;</th>
        </tr>
    </thead>
    <tbody class="table-group-divider align-middle">
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.MaGG)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TenSuKien)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhanTram)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ThoiGianBD)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ThoiGianKT)
                </td>
                <td>
                    <button type="button" class="btn control-padding" data-bs-toggle="modal" data-bs-target="#inforModal_@item.MaGG" data-bs-whatever="xxxxx">
                        <i class="bi bi-info-circle"></i>
                    </button>
                    <div class="modal fade" id="inforModal_@item.MaGG" tabindex="-1" aria-labelledby="inforModalLabel" aria-hidden="true" style="display: none;">
                        <div class="modal-dialog">
                            <div class="modal-content">

                                <div class="modal-header">
                                    <h1 class="modal-title fs-5" id="inforModalLabel">Information of @item.MaGG</h1>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>

                                <div class="modal-body text-start">
                                    <form class="w-100">
                                        <div class="mb-3">
                                            <label for="recipient-name" class="col-form-label">Thông tin ưu đãi</label>
                                            <textarea class="form-control" id="recipient-name" disabled>@item.ThongTinSuKien</textarea>
                                        </div>
                                    </form>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </div>
                    </div>

                    @Html.ActionLink(" ", "Edit", new { id = item.MaGG }, new { @class = "action-link bi bi-pencil", @style = "margin-right: 10px; text-decoration: none;" })

                    @*Delete*@
                    <button type="button" class="btn btn-danger rounded-circle rounded-5 control-padding" data-bs-toggle="modal" data-bs-target="#deleteModal_@item.MaGG">
                        <i class="bi bi-trash"></i>
                    </button>
                    <div class="modal fade" id="deleteModal_@item.MaGG" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h1 class="modal-title fs-5" id="deleteModalLabel">Xóa Ưu Đãi</h1>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <p>Bạn có muốn xóa Ưu Đãi @item.TenSuKien</p>
                                </div>
                                <div class="modal-footer">
                                    @using (Html.BeginForm("Delete", "managerDiscount", new { id = item.MaGG }, FormMethod.Post))
                                    {
                                        <button type="submit" class="btn btn-danger">Xóa</button>
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Đóng</button>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
@section css{
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/Areas/admin/CSS/Admin.css">

}
@section scripts{
    <script>

        $(document).ready(() => {
            $('#discountTable').DataTable({
                columnDefs: [{ orderable: false, targets: 5 }],
                "scrollY": "400px",
                "scrollCollapse": true,
                "paging": true,
                //select: true,
                processing: true,
                lengthMenu: [10, 25, 50, 100],
                responsive: true,
            })
        })

        function createNew() {
            window.location.href = '@Url.Action("Create")';
        }

        $(document).ready(function () {
            var buttonAddProduct = $('<button>', {
                id: 'buttonAddProduct',
                class: 'btn btn-primary text-light fw-bold me-3 ',
                text: 'Thêm Ưu đãi',
                click: createNew,
            });
            $('#discountTable_filter').prepend(buttonAddProduct);
        });


        $(document).ready(function () {
            $('#errorModal').modal('show');
        });
    </script>
}