KFC_Framework/Areas/admin/Controllers/managerOrderController.cs
using KFC_Framework.Dao;
using KFC_Framework.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KFC_Framework.Areas.admin.Controllers
{
    public class managerOrderController : Controller
    {
        private OrderDao orderDao = new OrderDao();
        private EmployeeDao employeeDao = new EmployeeDao();
        // GET: admin/managerOrder
        public ActionResult Index()
        {
            if (Session["UserRole"] != null && (Session["UserRole"].ToString() == "Nhân viên" || Session["UserRole"].ToString() == "Admin"))
            {
                var list = orderDao.getListOrders();
                return View(list);
            }
            else
            {
                TempData["Error"] = "Bạn không có quyền truy cập trang này.";
                return Redirect(Request.UrlReferrer.ToString());
            }
        }

        ////Edit
        [HttpGet]
        public ActionResult Edit(string id)
        {
            if (Session["UserRole"] != null && (Session["UserRole"].ToString() == "Nhân viên" || Session["UserRole"].ToString() == "Admin"))
            {
                DonDatHang ddh = orderDao.getByIdOrder(id);
                return View(ddh);
            }
            else
            {
                TempData["Error"] = "Bạn không có quyền truy cập trang này.";
                return Redirect(Request.UrlReferrer.ToString());
            }
        }

        //[HttpPost]
        [HttpPost]
        public ActionResult Edit(DonDatHang model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    orderDao.editOrder(model);
                    return RedirectToAction("Index");
                }
                return View(model);
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        public ActionResult exportBill(string id)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    DonDatHang donDatHang = orderDao.getByIdOrder(id);
                    List<CTDonDatHang> cTDonDatHang = orderDao.getDetailOrderById(id);
                    string matk = Session["MaTK"] as string;
                    string manv = employeeDao.getByMaTK(matk).MaNV;
                    orderDao.InsertBillInfo(donDatHang,cTDonDatHang, manv);
                    return RedirectToAction("Index");
                }
                return View(id);
            }
            catch
            {
                return View();
            }
        }
    }
}

KFC_Framework/Areas/admin/Views/managerOrder/Edit.cshtml
@model KFC_Framework.Models.DonDatHang

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/admin/Views/Shared/_LayoutAdmin.cshtml";
}

@Html.Action("_PartialErrorAccessRole", "Parital", new { area = "" })
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="container">
        <h2>CHỈNH SỬA ĐƠN HÀNG</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaDDH)

        <!--<div class="mb-3 row">
            @Html.LabelFor(model => model.MaKH, "Mã Khách Hàng", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-sm-10">-->
        @*@Html.DropDownListFor(model => model.MaKH, (IEnumerable<SelectListItem>)ViewBag.cutomerList, "Select Customer", new { @class = "form-control", id = "customerDropdown" })*@
        <!--@Html.ValidationMessageFor(model => model.MaKH, "", new { @class = "text-danger" })
            </div>
        </div>-->
        <div class="mb-3 row">
            @Html.LabelFor(model => model.MaKH, "Mã Khách Hàng", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaKH, new { htmlAttributes = new { @class = "form-control", id = "makh", disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.MaKH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="mb-3 row">
            @Html.LabelFor(model => model.TenNguoiNhan, "Tên Người Nhận", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenNguoiNhan, new { htmlAttributes = new { @class = "form-control", id = "tenNguoiNhan", disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.TenNguoiNhan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="mb-3 row">
            @Html.LabelFor(model => model.NgayDH, "Ngày Đặt Hàng", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="date" class="form-control" id="NgayDH" name="NgayDH" value="@Model.NgayDH.ToString("yyyy-MM-dd")" />
                @Html.ValidationMessageFor(model => model.NgayDH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="mb-3 row">
            @Html.LabelFor(model => model.NgayGH, "Ngày Giao Hàng", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="date" class="form-control" id="NgayGH" name="NgayGH" value="@Model.NgayGH.ToString("yyyy-MM-dd")" />
                @Html.ValidationMessageFor(model => model.NgayGH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="mb-3 row">
            @Html.LabelFor(model => model.HTThanhToan, "Hình Thức Thanh Toán", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HTThanhToan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HTThanhToan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="mb-3 row">
            @Html.LabelFor(model => model.HTGiaoHang, "Hình Thức Giao Hàng", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HTGiaoHang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HTGiaoHang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="mb-3 row">
            @Html.LabelFor(model => model.TriGia, "Trị Giá", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="number" class="form-control" id="trigia" name="trigia" value="@Model.TriGia" />
                @Html.ValidationMessageFor(model => model.TriGia, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="mb-3 row">
            @Html.LabelFor(model => model.TinhTrang, "Tình Trạng", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.TinhTrang, new SelectList(
                    new List<SelectListItem>
                    {
                        new SelectListItem { Text = "Đang vận chuyển", Value = "Đang vận chuyển" },
                        new SelectListItem { Text = "Đang xử lý", Value = "Đang xử lý" },
                        new SelectListItem { Text = "Hoàn thành", Value = "Hoàn thành" },
                        new SelectListItem { Text = "Đã hủy", Value = "Đã hủy" }
                    }, "Value", "Text"), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TinhTrang, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="mb-3 row">
            <div class="col-sm-12 text-center">
                <button type="submit" class="btn btn-danger fw-bold">SAVE</button>
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
            </div>

        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        //console.log($('#customerDropdown'))
        //$(document).ready(function () {
        //    $('#customerDropdown').change(function () {
        //        var selectedValue = $(this).val();
        //        if (selectedValue !== '') {
        //            $('#tenNguoiNhan').prop('disabled', true);
        //            $('#tenNguoiNhan').val(' ')
        //        } else {
        //            $('#tenNguoiNhan').prop('disabled', false);
        //        }
        //    });

        //    $('#customerDropdown').change(function () {
        //        var selectedCustomerId = $(this).val(); /
        //        var selectedCustomerName = $(this).find('option:selected').text(); // Lấy tên khách hàng được chọn
        //        $('#tenNguoiNhan').val(selectedCustomerName); // Cập nhật ô tên người nhận
        //    });
        //});
    </script>
}

KFC_Framework/Areas/admin/Views/managerOrder/Index.cshtml
@model IEnumerable<KFC_Framework.Models.DonDatHang>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/admin/Views/Shared/_LayoutAdmin.cshtml";
}

@Html.Action("_PartialErrorAccessRole", "Parital", new { area = "" })
<table id="orderTable" class="table-sm table table-striped table-light table-hover custom-thead-color">
    <thead class="table-dark">
        <tr>
            <th scope="col">
                Mã ĐH
            </th>
            <th scope="col">
                Mã KH
            </th>
            <th scope="col">
                Tên Khách hàng
            </th>
            <th scope="col">Trị giá</th>
            <th scope="col">Ngày đặt hàng</th>
            <th scope="col">Ngày nhận hàng</th>
            <th scope="col">Tình Trạng</th>
            <th scope="col">&#160;</th>
        </tr>
    </thead>
    <tbody class="class=" table-group-divider align-middle"">
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.MaDDH)
                </td>
                @if (item.MaKH == null)
                {
                    <td>
                        -------
                    </td>
                }
                else
                {
                    <td>
                        @Html.DisplayFor(modelItem => item.MaKH)
                    </td>
                }
                <td>
                    @Html.DisplayFor(modelItem => item.TenNguoiNhan)
                </td>
                <td class="text-end">
                    @String.Format("{0:#,##0} VNĐ", item.TriGia)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NgayDH)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NgayGH)
                </td>
                <td class="">
                    @switch (item.TinhTrang)
                    {
                        case "Đã hủy":
                            <span class="status bg-admin fw-medium text-light rounded-4 py-1 px-3">@item.TinhTrang</span>
                            break;
                        case "Chờ xử lý":
                            <span class="status bg-staff fw-medium text-light rounded-4 py-1 px-3">@item.TinhTrang</span>
                            break;
                        case "Đang vận chuyển":
                            <span class="status bg-customer fw-medium text-light rounded-4 py-1 px-3">@item.TinhTrang</span>
                            break;
                        case "Hoàn thành":
                            <span class="status bg-success-order bg-gradient rounded-4 py-1 px-3">@item.TinhTrang</span>
                            @*<span class="status bg-staff--warehouse fw-medium text-light rounded-4 py-1 px-3">@item.LoaiTK</span>*@
                            break;
                    }
                </td>

                <td class="text-end">
                    <button type="button" class="btn control-padding" data-bs-toggle="modal" data-bs-target="#inforModal_@item.MaDDH" data-bs-whatever="xxxxx">
                        <i class="bi bi-info-circle"></i>
                    </button>
                    <div class="modal fade" id="inforModal_@item.MaDDH" tabindex="-1" aria-labelledby="inforModalLabel" aria-hidden="true" style="display: none;">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h1 class="modal-title fs-5" id="inforModalLabel">Order information of @item.MaDDH</h1>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>

                                <div class="modal-body text-start">
                                    <form class="w-100">
                                        @if (item.MaKH != null)
                                        {
                                            <div class="mb-3">
                                                <label for="recipient-name" class="col-form-label">Mã Khách hàng</label>
                                                <input type="text" class="form-control" value="@item.MaKH" id="recipient-name" disabled>
                                            </div>
                                        }
                                        <div class="mb-3">
                                            <label for="phone" class="col-form-label">Số Điện Thoại Nhận</label>
                                            <input class="form-control" value="@item.SDTNhanHang" id="phone" disabled />
                                        </div>
                                        <div class="mb-3">
                                            <label for="email" class="col-form-label">Email</label>
                                            <input class="form-control" value="@item.Email" id="email" disabled />
                                        </div>
                                        <div class="mb-3">
                                            <label for="local" class="col-form-label">Địa chỉ nhận hàng</label>
                                            <input class="form-control" value="@item.DiaChiNhan" id="local" disabled />
                                        </div>
                                        <div class="mb-3">
                                            <label for="TypePay" class="col-form-label">Hình thức thanh toán</label>
                                            <input class="form-control" value="@item.HTThanhToan" id="TypePay" disabled />
                                        </div>
                                        <div class="mb-3">
                                            <label for="typeShip" class="col-form-label">Hình thức giao hàng</label>
                                            <input class="form-control" value="@item.HTGiaoHang" id="typeShip" disabled />
                                        </div>
                                    </form>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </div>
                    </div>


                    @Html.ActionLink(" ", "Edit", new { id = item.MaDDH }, new { @class = "action-link bi bi-pencil", @style = "margin-right: 10px; text-decoration: none;" })

                    @*@Html.ActionLink(" ", "Delete", new { id = item.MaDDH }, new { @class = "btn btn-danger rounded-circle rounded-5 control-padding action-link bi bi-trash", @style = "margin-right: 10px; text-decoration: none;" })*@

                    @*@Html.ActionLink(" ", "exportBill", new { id = item.MaDDH }, new { @class = "btn btn-warning rounded-circle rounded-5 control-padding action-link bi bi-receipt-cutoff", @style = "margin-right: 10px; text-decoration: none;" })*@
                    @if (item.TinhTrang != "Hoàn thành" && item.TinhTrang != "Đã hủy")
                    {
                        <button type="button" class="btn btn-warning rounded-circle rounded-5 control-padding" data-bs-toggle="modal" data-bs-target="#deleteModal_@item.MaDDH">
                            <i class="bi bi-receipt-cutoff"></i>
                        </button>
                    }
                    <div class="modal fade" id="deleteModal_@item.MaDDH" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h1 class="modal-title fs-5" id="deleteModalLabel">Xuất Hóa Đơn</h1>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <p>Bạn có muốn tạo hóa đơn cho mã <strong>@item.MaDDH</strong> này?</p>
                                </div>
                                <div class="modal-footer">
                                    @using (Html.BeginForm("exportBill", "managerOrder", new { id = item.MaDDH }, FormMethod.Post))
                                    {
                                        <button type="submit" class="btn btn-success">Tạo Hóa Đơn</button>
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Đóng</button>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        }
    </tbody>

</table>


@section css{
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/Areas/admin/CSS/Admin.css">
}
@section scripts{
    <script>
        $(document).ready(() => {
            $('#orderTable').DataTable({
                /*autoWidth: false,*/
                columns: [null, { width: '100px' }, { width: '150px' }, { width: '113.675px' }, { width: '212.413px' }, { width: '212.413px' }, { width: '144.163px' }, { width: '131.413px' }],
                columnDefs: [{ orderable: false, targets: 7 }],
                "scrollY": "400px",
                "scrollCollapse": true,
                "paging": true,
                select: false,
                processing: true,
                lengthMenu: [10, 25, 50, 100],
                responsive: true,
            })
        });

        $(document).ready(function () {
            $('#errorModal').modal('show');
        });
    </script>
}